from __future__ import annotations

from enum import StrEnum


class CandidateAction(StrEnum):
    DO_NOTHING = "DO_NOTHING"
    PREPARE_PAYMENT_LINK = "PREPARE_PAYMENT_LINK"
    ESCALATE_FOR_REVIEW = "ESCALATE_FOR_REVIEW"
    WAIT_FOR_MORE_FACTS = "WAIT_FOR_MORE_FACTS"


class PolicyDecisionKind(StrEnum):
    APPROVE = "APPROVE"
    DENY = "DENY"
    ESCALATE = "ESCALATE"


class PolicyReasonCode(StrEnum):
    POLICY_MISSING = "POLICY_MISSING"
    POLICY_DISABLED = "POLICY_DISABLED"
    CASE_CLOSED = "CASE_CLOSED"
    PAYMENT_ALREADY_CAPTURED = "PAYMENT_ALREADY_CAPTURED"
    ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
    INVALID_CANDIDATE_ACTION = "INVALID_CANDIDATE_ACTION"
    ACTION_NOT_ALLOWLISTED = "ACTION_NOT_ALLOWLISTED"
    NON_POSITIVE_AMOUNT = "NON_POSITIVE_AMOUNT"
    CURRENCY_MISSING = "CURRENCY_MISSING"
    AMOUNT_LIMIT_EXCEEDED = "AMOUNT_LIMIT_EXCEEDED"
    PROBABILITY_BELOW_THRESHOLD = "PROBABILITY_BELOW_THRESHOLD"
    EXPECTED_VALUE_BELOW_THRESHOLD = "EXPECTED_VALUE_BELOW_THRESHOLD"
    ATTEMPT_LIMIT_EXCEEDED = "ATTEMPT_LIMIT_EXCEEDED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    BUDGET_LIMIT_EXCEEDED = "BUDGET_LIMIT_EXCEEDED"
    INSUFFICIENT_FACTS = "INSUFFICIENT_FACTS"
    POLICY_CONFIGURATION_AMBIGUOUS = "POLICY_CONFIGURATION_AMBIGUOUS"
    ALL_POLICY_CHECKS_PASSED = "ALL_POLICY_CHECKS_PASSED"
